---
name: Piwik
description: Piwik is a powerful self-hosted alternative to Google Analytics services that can be deployed on top of a LAMP stack in Linux.

parameters:
  hostname:
    name: Hostname
    description: The hostname of the HTTP request, the hostname of the Piwik Server

  database_password:
    name: Database Password
    description: The database Password for your database

  variant:
    name: Variant
    description: Variant of Piwik

  database:
    name: Database
    description: Database you want to configure

  force_https:
    name: Force HTTPS
    description: If you want to force https

  use_forwarded_for:
    name: Use forwarded for
    description: Add HTTP header for identifying the originating IP address of a client connecting to a web server through an HTTP proxy or load balancer.

  use_forwarded_host:
    name: Use forwarded host
    description: Add header for identifying the original host requested by the client in the Host HTTP request header
