engines:
  duplication:
    enabled: true
    config:
      languages:
        ruby:
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Metrics/BlockLength:
        enabled: false
      Rubocop/Style/ClassAndModuleChildren:
        enabled: false
ratings:
  paths:
    - "lib/**"
exclude_paths:
  - "lib/puppet_x/wildfly/gems"
