require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'lib/puppet_x/wildfly/gems/**/*'
    - 'pkg/**/*'
    - 'coverage/**/*'
    - 'files/**/*'
    - 'manifests/**/*'
    - 'Rakefile'
    - 'Gemfile'
    - '*.markdown'
    - '*.md'

Style/Encoding:
  Enabled: true

Style/VariableName:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/RedundantSelf:
  Enabled: true

Style/UnlessElse:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/Next:
  Enabled: true

Eval:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

Lambda:
  Enabled: false

LineLength:
  Enabled: false

AccessorMethodName:
  Enabled: false

MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: true

Lint/UnusedMethodArgument:
  Description: 'Checks for unused method arguments.'
  Enabled: false

Lint/UnusedBlockArgument:
  Description: 'Checks for unused block arguments.'
  Enabled: false

BlockNesting:
  Enabled: false
