language: ruby
sudo: false
cache:
  directories:
  - vendor/bundle
  - wget_cache
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
bundler_args: --without acceptance
before_install:
  -  gem update --system 2.1.11
script:
  - bundle exec rake syntax
  - bundle exec rake lint
  - bundle exec rake spec
notifications:
  email:
    - biemond@gmail.com
    - junior.jairo1@gmail.com
env:
  - PUPPET_VERSION=4.4.2
  - PUPPET_VERSION=4.6.2
  - PUPPET_VERSION=4.8.2
  - PUPPET_VERSION=4.9.2
matrix:
  include:
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent TEST_profile=wildfly:10.1.0 BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/debian-7 bundle
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-1404 bundle
      script: bundle exec rake beaker
      services: docker
      sudo: required
      bundler_args: --with acceptance
