sudo: false
language: ruby
bundler_args: --without kitchen
script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake spec
matrix:
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="= 3.7.3"
  - rvm: 1.9.3
    env: PUPPET_VERSION="= 3.7.3" FUTURE_PARSER="yes"
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 4.0"
deploy:
  provider: puppetforge
  on:
    tags: true
    branch: master
  user:
    secure: "Gp1R8um3RCFEi52xkeeTGffffAB8ZOA9q2maoi8LE+WEOIuwoOxz+bsyNnw6KctYBGR1xAZ7RdJica0NGk2WnIUVMixVfIEk6fw0YKILsBnFSuuVaNGK+OKqWo9M6HczTZw/HCs+5w1T9xOWGP8zxoTx4SLVKPi95TwCaGIAmdE="
  password:
    secure: "eBjQEB+9AOjmVlBuGZSvH1Y4/Ty7YXXW8h6rOsA7BNOQi1bKl+RyC4OunWOQq+NCfXkVRodhELuAb4DMSJ2OC9OXEW97ekcb7HVMX6lejz3lNtooek3QwAs6Jj0p4P6o6giNqYguEqOIrbXTap1HEyL+XdNnfKY4I0NIY7ap18A="
