---
Gemfile:
  optional:
    ":development":
      - gem: beaker
        version: '~> 5.0'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 1.0'
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      # Prevent beaker-puppet from being installed on Ruby > 3.1 until
      # beaker-puppet supports newer Rubies (PA-6136)
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 3.0'
        condition: Gem::Requirement.create('< 3.2.0').satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))
      - gem: async
        version: '~> 1'
      - gem: beaker-module_install_helper
      - gem: beaker-puppet_install_helper
      - gem: nokogiri
    ":system_tests":
      - gem: voxpupuli-acceptance

appveyor.yml:
  delete: true
.travis.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
# We still use the Vox acceptance Rake task instead of Litmus
Rakefile:
  requires:
    - require: voxpupuli/acceptance/rake
      conditional: Gem.loaded_specs.key? 'voxpupuli-acceptance'
