---
name: RubyonRails Webframework
description: RubyonRails webframework on Raptor passenger

features:
  - monitoring
  - time
  - security
  - logging

distributions:
  - CentOS-7
  - CentOS-6
  - RedHat-6
  - RedHat-7

parameters:
  db:
    name: Database Engine
    description: Select Database engine.

  ruby:
    name: Ruby
    description: Select Passenger Engine

  http_server:
    name: HTTP server

  version:
    name: Passenger Version
    coerce: int
    enum:
      5:
        name: Passenger Version 5
      4:
        name: Passenger Version 4

  provider:
    name: Passenger Provider
    enum:
      package:
        name: Passenger Package
      gem:
        name: Passenger Gem

  manage_web_server:
    name: Manage webserver installation
    description: Install apache and Manage Apache service.
