---
name: Gitlab CI
description: |
  Gitlab enables you to do Git hosting, Issue hosting, Continuous Integration etc.

features:
  - security
  - logging

distributions:
  - Ubuntu-16.04
  - Ubuntu-18.04
  - Ubuntu-20.04
  - Debian-8

parameters:
  domain:
    name: Public domain
    description: Public domain for your Gitlab installation

  time_zone:
    name: Timezone
    description: Select the timezone your Gitlab installation is running in.

  registry:
    name: Enable Gitlab Docker container registry
    description: >-
      Enable Gitlab to host a Docker container registry. See
      https://docs.gitlab.com/ee/user/packages/container_registry/ for more
      information.

  default_theme:
    name: Default theme
    description: Default theme for your Gitlab installation

  terminate_https:
    name: Terminate HTTPS
    description: >-
      Enable if you want Gitlab to take care of SSL termination. Disable if you
      use e.g. `::role::web::haproxy` in front of your Gitlab installation.

  redirect_http_to_https:
    name: Redirect HTTP to HTTPS
    description: Enable to make Gitlab redirect HTTP requests to HTTPS.

  email_enabled:
    name: Enable email
    description: >-
      Enable Gitlab to send email (for password recovery, account registration,
      issue updates etc.)

  email_display_name:
    name: Email display name
    description: Name to use when sending email (will be visible name in email inbox).

  gitlab_rails:
    name: Options passed directly into 'gitlab_rails' hash in the `gitlab.rb` config file.
    advanced: true

  nginx:
    name: Options passed directly into 'nginx' hash in the `gitlab.rb` config file.
    advanced: true

  registry_ssl_cert:
    name: SSL cert for registry
    advanced: true

  registry_ssl_key:
    name: SSL cert key for registry
    advanced: true

  registry_domain:
    name: Public domain for docker registry
    advanced: true
