---
sudo: false
language: ruby
cache: bundler
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
script: bundle exec rake test SPEC_OPTS='--format documentation'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
env:
  matrix:
    - PUPPET_VERSION="~> 3.8.0"
    - PUPPET_VERSION="~> 4.4.0"
matrix:
  fast_finish: true
