fixtures:
  repositories:
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql"
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo"
    concat:
      repo: "git://github.com/puppetlabs/puppetlabs-concat"
      branch: "1.2.x"
    apache: "git://github.com/puppetlabs/puppetlabs-apache"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    postgresql: "git://github.com/puppetlabs/puppetlabs-postgresql"
  symlinks:
    redmine: "#{source_dir}"
