fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    systemd: "https://github.com/voxpupuli/puppet-systemd"
    sshkeys_core: "https://github.com/puppetlabs/puppetlabs-sshkeys_core"
