type Eit_types::Gitlab::Runner::Config = Struct[{
  'working_directory'  => Optional[Stdlib::Unixpath],
  'ca_file'            => Optional[Stdlib::Unixpath],
  'url'                => Optional[Stdlib::HTTPSUrl],
  'registration-token' => Optional[String],
  'image'              => Optional[Eit_types::DockerImage],
  'tlsverify'          => Optional[Boolean],
  'privileged'         => Optional[Boolean],
  'disable-cache'      => Optional[Boolean],
  'volumes'            => Optional[Array[Stdlib::Unixpath]],
  'concurrency'        => Optional[Integer[1, 10]],
  'check_interval'     => Optional[Integer],
  'shutdown_timeout'   => Optional[Integer],
  'connection_max_age' => Optional[String],
}]
