type Repository::Mirrors::Apt_Settings = Struct[{
  enable         => Boolean,
  mirror_url     => Optional[String],
  repodir        => String,
  package_format => Optional[Enum['deb']],
  architectures  => Optional[Array[Enum['amd64', 'arm64', 'all']]],
  deb_sync_type  => Optional[Enum['debmirror']],
  dists          => Optional[Array[Enum[
    'focal',
    'focal-backports',
    'focal-security',
    'focal-updates',
    'jammy',
    'jammy-backports',
    'jammy-security',
    'jammy-updates',
    'noble',
    'noble-backports',
    'noble-security',
    'noble-updates',
  ]]],
  sections       => Optional[Array[Enum[
    'main',
    'restricted',
    'universe',
    'multiverse',
    'puppet7',
    'stable',
  ]]],
  key_ids        => Optional[Array[String[40,40]]],
  key_source     => Optional[String],
  key_server     => Optional[Eit_types::URL],
}]
