---
name: Fast-CGI
description: Apache Webserver with Fast-CGI setup to run executables, following the rules of <a href="http://en.wikipedia.org/wiki/Common_Gateway_Interface" target="_blank">CGI</a>.

features:
  - Monitoring
  - Time
  - Security
  - Logging

distributions:
  - CentOS-7
  - CentOS-6
  - RedHat-6
  - RedHat-7

parameters:
  url:
    name: URL

  http_server:
    name: HTTP server
    enum:
      apache:
        name: Apache
