---
name: PHP webserver
description: Webserver with PHP.
logo: php-med-trans.png
suggests:
  - role::webframeworks::drupal
  - role::webframeworks::wordpress

features:
  - Monitoring
  - Time
  - Security
  - Logging

distributions:
  - CentOS-7
  - CentOS-6
  - RedHat-6
  - RedHat-7

parameters:
  url:
    name: URL

  ssl:
    name: SSL
    description: Enable SSL Encryption (https)

  http_server:
    name: HTTP server
    enum:
      nginx:
        name: nginx
      apache:
        name: Apache

  opcodecache:
    name: Opcode cache
    enum:
      apc:
        name: APC
      xcache:
        name: xcache

  mysql:
    name: Enable MySQL/MariaDB
