---
name: Nodejs webserver
description: Nodejs

features:
  - Monitoring
  - Time
  - Security
  - Logging

distributions:
  - CentOS-7
  - CentOS-6
  - RedHat-6
  - RedHat-7

parameters:
  url:
    name: URL
    description: url to your website.
