---
name: Phusion Passenger
description: Phusion Passenger

features:
  - Monitoring
  - Time
  - Security
  - Logging

distributions:
  - CentOS-7
  - CentOS-6
  - RedHat-6
  - RedHat-7

parameters:
  url:
    name: URL

  http_server:
    name: HTTP server
    type: select
    enum:
      apache:
        name: Apache

  version:
    name: Passenger Version
    enum:
      5:
        name: Passenger Version 5
      4:
        name: Passenger Version 4

  provider:
    name: Passenger Provider
    enum:
      package:
        name: Install from distribution repository
      gem:
        name: Install as Ruby gem

  manage_web_server:
    name: Manage Web server
