---
name: PHPFPM
description: PHP-FPM (FastCGI Process Manager) is an alternative PHP FastCGI implementation with some additional features useful for sites of any size, especially busier sites.

features:
  - Monitoring
  - Time
  - Security
  - Logging

distributions:
  - CentOS-7
  - CentOS-6
  - RedHat-6
  - RedHat-7

parameters:
  url:
    name: URL

  http_server:
    name: HTTP server
    enum:
      apache:
        name: Apache
      nginx:
        name: nginx

  opcodecache:
    name: Opcode cache
    enum:
      apc:
        name: APC

  ssl:
    name: SSL
