---
.travis.yml:
  docker_sets:
    - set: docker/centos-7
    - set: docker/debian-9
    - set: docker/ubuntu-14.04
    - set: docker/ubuntu-16.04
  secure: "OKYO+/kY1KB9EH0pB30AU6E2c5SZbNql+Klg+sb1/LMi+ADjyNEzcfTP6aUhnYedKJf5m8rfycc81UPuUeKaR/U/mPwR1R5OKh+S1KL1yzrRdxdpmLWMX14nBFbAZYvSTe/bPbxhngjW84uHRF2zkkSxKStsIzyy2DcTYayaWZ0="
spec/spec_helper.rb:
  spec_overrides:
    - "require 'spec_helper_corosync'"
    - "require 'spec_helper_methods'"
