name 'jtopjian-reprepro'
version '3.0.0'
source 'git://github.com/jtopjian/puppet-reprepro.git'
author 'jtopjian, saz, camptocamp'
license 'Apache 2.0'
summary 'Assists in the creation of reprepro-based repositories'
description 'This module assists in the creation of reprepro-based debian-package repositories. It is compatible with both Debian and Ubuntu. Although this module has no dependencies itself, several modules are needed for a more practical deployment. Please see the README.md file for a full example. This module was based off of the exist module by saz (https://github.com/saz) and camptocamp (https://github.com/camptocamp)'
project_page 'https://github.com/jtopjian/puppet-reprepro'
dependency 'puppetlabs/concat', '>=0.2.0'
