---
name: Puppet CI for shellcheck, erb, epp and lint

"on":
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  puppet_ci:
    name: Puppet CI
    runs-on: ubuntu-latest
    container:
      image: harbor.obmondo.com/obmondo/dockerfiles/puppet-ci:1.1.0
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: shellcheck
        if: ${{ github.event.pull_request.merged == false }}
        run: /usr/local/bin/check_sh.rb

      - name: lint_epp
        if: ${{ github.event.pull_request.merged == false }}
        run: /usr/local/bin/check_epp.sh

      - name: lint_erb
        if: ${{ github.event.pull_request.merged == false }}
        run: /usr/local/bin/check_erb.sh

      - name: lint_puppet
        if: ${{ github.event.pull_request.merged == false }}
        run: |
          /usr/local/bin/check_pp.sh
          /usr/local/bin/check_lint.sh

      - name: lint_secret
        if: ${{ github.event.pull_request.merged == false }}
        run: |
          /usr/local/bin/check_secrets.sh modules/enableit

      - name: lint_json
        if: ${{ github.event.pull_request.merged == false }}
        run: /usr/local/bin/check_json.sh

  yamllint:
    uses: Obmondo/gitea-actions/.gitea/workflows/yamllint.yml@main
    with:
      dirs: "."
