#! /bin/bash
#
#############################################################################
#
# ansoftrsm:   Ansoft Remote Simulation Manager init script
#
# Author:      Ansoft LLC
#
# chkconfig:   345 90 10
# description: Ansoft Remote Simulation Manager init script
#
### BEGIN INIT INFO
# Provides: ansoftrsm
# Required-Start: $local_fs $network $syslog
# Required-Stop:
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description:  Ansoft Remote Simulation Manager init script
# Description:  Ansoft Remote Simulation Manager init script
### END INIT INFO


#----------------------------------------------------------------------
RenameFunction()
{
  if [ $# -lt 2 ] ; then
    echo "Local function syntax: Rename function <old function name> <new function name>"
    return 0
  fi

  # Define new function
  new_fn=$(typeset -f status |perl -lpe 'if($.==1){s@'"$1"'@'"$2"'@}')
  eval "$new_fn"

  # Undefine old function
  unset "$1"

  return 1
}

#----------------------------------------------------------------------
# Alias functions
#----------------------------------------------------------------------
shopt -s expand_aliases
if [ -f /lib/lsb/init-functions ]; then
  . /lib/lsb/init-functions
  alias START_DAEMON=start_daemon
  alias LOG_SUCCESS=log_success_msg
  alias LOG_FAILURE=log_failure_msg
  alias LOG_WARNING=log_warning_msg

elif [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions

  # Rename status function to initd_status
  RenameFunction status initd_status

  STATUS()
  {
    initd_status "$@" > /dev/null 2>&1
    return $?
  }

  alias START_DAEMON=daemon
  alias LOG_SUCCESS=success
  alias LOG_FAILURE=failure
  alias LOG_WARNING=passed
else
  echo "Error: $0 does not support this operating system." 1>&2
  exit 1
fi


# Target of script
target="/local/AnsysEM/rsm/Linux/ansoftrsmservice"

# Specify user as whom script is to be run
start_as_user="root"

shopt -s expand_aliases

if [ ! -e "${target}" ] ; then
  echo "Ansoft Remote Simulation Manager: FAILED"
  echo "${target} does not exist." 1>&2
  exit 1
elif [ ! -x "${target}" ] ; then
  echo "Ansoft Remote Simulation Manager: FAILED"
  echo "${target} does not include execute permissions." 1>&2
  exit 1
fi

# Call target -- get stdout but not stderr
"${target}" $@ -runas "${start_as_user}"
retval=$?
exit $retval
