HOSTS:
  el7:
    roles:
      - default
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc

  el8:
    roles:
      - el8
    platform:   el-8-x86_64
    box:        generic/centos8
    hypervisor: vagrant
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/8/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc

CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
