---
language: ruby
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - gem update bundler
rvm:
  - 2.1.0
  - 2.4.0
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.0.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.1.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.2.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.3.0" STRICT_VARIABLES=yes
  - PUPPET_GEM_VERSION="~> 5.5.0" STRICT_VARIABLES=yes
matrix:
  exclude:
