fixtures:
  forge_modules:
    apt:
      repo: "puppetlabs/apt"
      ref: "2.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.25.1"
    yumrepo_core:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.0"
    concat:
      repo: "puppetlabs/concat"
  symlinks:
    curator: "#{source_dir}"
