fixtures:
  repositories:
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
