---
name: Docker
description: Docker setup

parameters:
  docker_lib_dir:
    name: Docker Library folder
    description: Docker intallation directory

  fixed_cidr:
    name: Fixed CIDR
    description: IPv4 subnet for fixed IPs.

  bip:
    name: Bridge IP
    description: Docker's network bridge IP, in CIDR notation

  default_gateway:
    name: Default gateway
    description: IPv4 address of the container default gateway. This address must be part of the bridge subnet (which is defined by bridge)

  bridge_interface:
    name: Bridge Interface
    description: Default Interface for new containers

  instances:
    name: Instances
    description: The docker instances to be created

  compose_instances:
    name: Compose Instances
    description: manage or create docker instances using docker compose file

  manage_compose:
    name: Manage compose
    description: If you want to manage your own docker compose instances/files.

  networks:
    name: Networks
    description: Networks used to establish communication between Docker containers and the outside world via the host machine where the Docker daemon is running.

  dns:
    name: DNS
    description: Custom dns server address

  dns_search:
    name: DNS Search
    description: Custom dns server domains

  insecure_registries:
    name: Insecure registries
    description: The registries not having either valid registry certificate or is not using TLS.

  users:
    name: Users
    description: Users part of docker

  enable_cadvisor:
    name: Enable cadvisor
    description: Whether you want to enable cadvisor or not

  prune_system:
    name: Prune System
    description: If you want to prune docker systems. If you enable this, a cron will run daily which allows you to clean up unused images

  prune_volume:
    name: Prune Volume
    description: If you want to prune docker Volume. If you enable this, a cron will run daily which removes all unused local volume

  compose_version:
    name: Compose version
    description: Docker compose version which you want to install

  registry:
    name: Registry
    description: The docker registry which you want to use to pull and push images too
