---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - rm -f Gemfile.lock
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test_with_coveralls
  - rvm: 2.4.4
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=rubocop
  - rvm: 2.5.1
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=build DEPLOY_TO_FORGE=yes
branches:
  only:
  - master
  - /^v\d/
notifications:
  email: false
  irc:
    on_success: always
    on_failure: always
    channels:
      - "chat.freenode.org#voxpupuli-notifications"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "QgYuMhjO7T7tpV7L1l06+rba9wW6yh9mOkr/5XZ+MKt5omuc9BsJVHEChJfCyPZbxyMRD635lTnxzLkQeWS1WzcxyxYHQv4gB8gVumbrixDbAWzLi9GUpvGgcn/i8IaVePQStwMZxLCnYbm6ghb85m5uFuHC53sT3Q3GSW9LZdGY1WzYLIg9NClxReT2Nmxiz0GBEn5Vln+dtFHCYrQoqjJbrIvey3hrGbSZkEXP8BblyEzKSxgbFklSKxtnC2kmTpwVmkRKU04dzgess/s4i/2qaCFfakN8RVJnb8TzAC7UWgOdcY0vsjMzSR71r29cSllHsutN/pU8pjukYmBgvKSTdgp54H9PST1z/tjpjtqFMVDeylrWCt0WWxG2M0mCdk414/Atft49LDAoscLugKOPHEStVpLLnu6rd6Q7l67cZwR0YxnaxKXi7/cQ5p703oubxJ6RtMkucCuk1HNo04JBgOPi1clKgOpaV37Kyk9cTzVrBaVbqYSiMJrFXuKQQ+TSibGq2M0XfJxNI784qm/5tOi/62CkkdN4SqYlbWldRtTg4hdfqtROyrUkSJEqINakI7OPtfGw2jjYML6IvLsz0C5/vhTrXPpxdo1r5GcB8EMC7yyXh/DGK8F+lCwltegCK7KDHCgzl65dmn68sgZb9kFpd5TD9s48MP4cKVU="
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish the build marked with "DEPLOY_TO_FORGE"
    condition: "$DEPLOY_TO_FORGE = yes"
