HOSTS:
  ubuntu-trusty:
    roles:
      - master
    platform: ubuntu-14.04-x64
    image: ubuntu:trusty
    hypervisor: docker
    docker_preserve_image: true
    docker_cmd: '["/sbin/init", "/usr/sbin/sshd", "-D"]'
    docker_container_name: "beaker-influxdb-ubuntu-trusty"
    docker_image_commands:
      # ensure that upstart is booting correctly in the container
      - 'rm /usr/sbin/policy-rc.d && rm /sbin/initctl && dpkg-divert --rename --remove /sbin/initctl && apt-get update && apt-get install -y net-tools wget && locale-gen en_US.UTF-8'
CONFIG:
  log_level: debug
  type: foss
