---
fixtures:
  repositories:
    augeas: https://github.com/camptocamp/puppet-augeas.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    concat: https://github.com/voxpupuli/puppet-alternatives.git
    mailalias_core: https://github.com/puppetlabs/puppetlabs-mailalias_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
