fixtures:
  repositories:
    apt: "git://github.com/puppetlabs/puppetlabs-apt"
    translate: "git://github.com/puppetlabs/puppetlabs-translate"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    inifile: "git://github.com/puppetlabs/puppetlabs-inifile"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    mount_core:
      repo: https://github.com/puppetlabs/puppetlabs-mount_core.git
      puppet_version: ">= 6.0.0"
