class role::scanner::openvas (
  Stdlib::Absolutepath   $install_dir                  = '/opt/obmondo/docker-compose/openvas',
  Boolean                $install                      = true,
  Stdlib::Host           $web_bind_address             = '127.0.0.1',
  Stdlib::Port           $web_port                     = 9392,
  Enum['service_notus']  $openvasd_mode                = 'service_notus',
  Eit_types::AddressPort $openvasd_addressport         = '0.0.0.0:80',
  Stdlib::Absolutepath   $storage_path                 = '/var/lib/openvas/22.04/vt-data/nasl',
  String                 $registry                     = 'registry.community.greenbone.net/community',
  Eit_types::Version     $vulnerability_tests_version  = '202502250742',
  Eit_types::Version     $notus_data_version           = '202502250410',
  Eit_types::Version     $scap_data_version            = '202502240506',
  Eit_types::Version     $cert_bund_data_version       = '202502250409',
  Eit_types::Version     $dfn_cert_data_version        = '202502250401',
  Eit_types::Version     $data_objects_version         = '202502250505',
  Eit_types::Version     $report_formats_version       = '202502250500',
  Eit_types::Version     $gpg_data_version             = '1.1.0',
  Eit_types::Version     $redis_server_version         = '1.1.0',
  Eit_types::Version     $pg_gvm_version               = '22.6.7',
  Eit_types::Version     $gsa_version                  = '24.3.0',
  Eit_types::Version     $gvmd_version                 = '25',
  Eit_types::Version     $openvas_scanner_version      = '23.15.4',
  Eit_types::Version     $ospd_openvas_version         = '22.8.0',
  Eit_types::Version     $gvm_tools_version            = '25',
  Eit_types::Version     $feed_release_version         = '24.10',
  Stdlib::Absolutepath   $data_mount_path              = '/mnt',
  Stdlib::Absolutepath   $gvm_data_path                = '/var/lib/gvm',
  Stdlib::Absolutepath   $openvas_plugins_path         = '/var/lib/openvas/plugins',
  Stdlib::Absolutepath   $redis_socket_path            = '/run/redis',
  Stdlib::Absolutepath   $gvmd_socket_path             = '/run/gvmd',
  Stdlib::Absolutepath   $ospd_socket_path             = '/run/ospd',
  Stdlib::Absolutepath   $psql_data_path               = '/var/lib/postgresql',
  Stdlib::Absolutepath   $psql_socket_path             = '/var/run/postgresql',
  Stdlib::Absolutepath   $openvas_config_path          = '/etc/openvas',
  Stdlib::Absolutepath   $openvas_log_path             = '/var/log/openvas',
  Stdlib::Absolutepath   $notus_path                   = '/var/lib/notus',
) {
  contain role::virtualization::docker
  contain profile::scanner::openvas
}
