---
fixtures:
  repositories:
    cron: https://github.com/puppetlabs/puppetlabs-cron_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
