---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/voxpupuli/puppet-augeasproviders_core
    augeasproviders_shellvar: https://github.com/voxpupuli/puppet-augeasproviders_shellvar
    inifile: https://github.com/puppetlabs/puppetlabs-inifile
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
