---
name: Backup MySQL/MariaDB
description: Backup of MySQL/MariaDB using LVM snapshots

parameters:

  backup_hour:
    name: Backup hour
    description: Time of day to do backup. Minutes will be randomized from FQDN.

  ignore_tables:
    name: Ignore tables
    description: List of tables that will be ignored in the snapshot.

  lvm_extents_min_required:
    name: LVM extents required
    description: |
      The minimum allowed percentage of available extents before the snapshot backup will fail.
