---
.travis.yml:
  secure: "xwp69Nk5akckY84I/UecQOJx1guhKFscwR16AURDw/A2oO6uY2T8iHqWN+i0jrQ4rB+EZK76dTvDZiNIOBByPc0GC4Hn53L2wy0uEz41Sd/Ys4gZviIFjY81y2jEeFa2MFPAI5KWCBFk4vPOoT8raYpkBA37ux6kvm2bemmqqSQ="
  docker_sets:
    - set: centos6-64
    - set: centos7-64
    - set: centos8-64
    - set: debian8-64
    - set: debian9-64
    - set: debian10-64
    - set: ubuntu1604-64
    - set: ubuntu1804-64
spec/spec_helper_acceptance.rb:
  unmanaged: false
