.travis.yml:
  forge_password: "oPMSsrCO57aXWIaGIhLbJ+ea6O38B3akaH6+hBanT73cnXZivOLaCySaiktsUE/05P7HbeYNHualqdHdYyUt9bbHfJbbHn0y+7cGI71Is1Z+vQwlOOdBeS+LYsyJ/STp0/GWUvsAmGGEl8mfJfVStb/KyVWHg1IZRnqvOdAZOog="
