# Class: dmcrypt::core
#
# Setup basic stuff needed for dmcrypt
#
# Set the $host_secret parameter if you want to use only
# one secret/key per host for all the later setup devices in
# this node. In this case you don't get a new dmcrypt::key 
# again for each device if you pass host_secret=true also to 
# dmcrypt::encryption and dmcrypt::open.
#
# == Name
#   Unused
# == Parameters
# [*host_secret*] If one secret/key per host should be used
#   Optional. Defaults to 'false'
#
# [*secret*] A secret to be used in the key, instead of
#   get a secret generated by puppet-secret. 
#   Optional.
#
# == Dependencies
#
# dmcrypt::key, Packages: cryptsetup and wip: all handled by
# this class.
#
# == Authors
#
#  Jan Alexander Slabiak <j.slabiak@telekom.de>
#  Danny Al-Gaaf <d.al-gaaf@telekom.de>
#
# == Copyright
#
# Copyright 2013 Deutsche Telekom AG
#
class dmcrypt::core (
  $host_secret = false,
  $secret      = undef,
){
  package {['cryptsetup','wipe']:
    ensure => installed
  }

  if $host_secret == true {
    # in this case already defined!
    $secret_name = "dmcrypt-${::hostname}"

    dmcrypt::key { "${secret_name}":
      key_name      => $secret_name,
      custom_secret => $secret,
    }
  }

}
