---
sudo: false
language: ruby
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.8.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
script:
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
bundler_args: --without system_tests
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock .gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
notifications:
  on_success: change
  on_failure: change
