---
name: Redis
description: Redis setup

parameters:
  bind:
    name: Bind
    description: IP address of the interface for Redis to bind

  default_port:
    name: Port
    description: The port Redis server runs on.
